- id: no_commit_to_master
  name: no commit to master
  description: Define the master branch as a restricted branch
  entry: no_commit_to_master.sh
  language: script
  always_run: true
- id: commitizen
  name: commitizen check
  description: Check whether the current commit message follows commiting rules.
  entry: cz check
  args: [--allow-abort, --commit-msg-file]
  language: python